### ISSUE TITLE
Question: Disable string presence validation

### ISSUE THREAD

**Issue by ypresto** [SchemaPlus/schema_validations#49]
I have some of `VARCHAR(255) NOT NULL DEFAULT ""` columns.
It is intended not to use nil, because column will be set to empty string when user leave the form (input tag) blank. It can be both nil or empty string without `NOT NULL`.
So I want to skip presence validation only for string column (or conditionally allow_blank).
How do I implement this?

IMO it can be option of this library:

```
config.allow_blank_string = true
```

or to automatically skip presence validation on `DEFAULT ""` text/string column.

**Comment by boazy** [comment]
I think this is the same as issue #18. Can you confirm?

The current behavior is obviously wrong, but I guess it will be troublesome to change due to compatibility reasons. A configuration option can solve that.
For a temporary workaround you can try @ronen's suggestion:
```ruby
class MyModel < ActiveRecord::Base
  schema_validations except: :my_column_name
end
```
This is useful if you just have a few fields where you need to avoid presence validation.

**Comment by ypresto** [comment]
Yes, that's same issue..! Hmm, I have 7 columns to except in single model and gave up to use the gem this time...

**Comment by boazy** [comment]
A pull request has been open to fix it. I'm closing this issue and tracking everything in #18.

**Comment by boazy** [comment]
Issue is solved, but we're now considering it a bug, so the configuration option is removed. You can just upgrade to the latest version and you'll no longer have presence validation when an empty default value is defined (there will still be presence validation when using non-empty default values).
